### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dougmassay** [Sigil-Ebook/IconThemes#2]
Question: what exactly are we looking to Release with our Appveyor script? Do we want to generate each of the alternative colors of "material" (named in the python script), and "legacy"? As well as allowing for any newly contributed themes, obviously. I don't see much point in re-releasing the 3 themes that are already a part of Sigil, myself, but will concede to the consensus, here.

**Comment by kevinhendricks** [comment]
Yes, we release all of the colour variants of material, and legacy as .rcc files.  No main or fluent.

**Comment by dougmassay** [comment]
Thanks! I'll try to have something working generally tomorrow night.

**Comment by dougmassay** [comment]
I added appveyor support. I modified the ChangeMaterialThemeColor script so that I could import it more easily into my python ci script. It still worked fine for me on Windows and Linux, but let me know if I broke anything that I overlooked.

For now, it will create a Draft release with all .rcc files attached whenever a tag is pushed to github. For now, the tag shouldn't be annotated or signed for things to work correctly. I've tested using a tag template of "2020-10-09-1" and it seems to work fine. The extra digit after the date is in case we screw up and need to create two tags on the same day. :)

You can try it if you like: draft releases are easy to delete -- as are  tags. I'm going to push the first one now. We can edit/publish it or delete it until we're ready. Just let me know.

It might need some tweaking, but the functionality is there.

**Comment by dougmassay** [comment]
In case that was unclear: this is what I'm doing from my local repo to  have appveyor make the draft release:

```
git tag 2020-10-10-1
git push origin 2020-10-10-1
```

**Comment by kevinhendricks** [comment]
Looks great!  I will push a Readme change just to see how things work.

In the current Readme I tell people the typical path on macOS to the user's Sigil preferences folder.  I left blank that path for Windows and Linux.

If you let me know what path or paths to put for both platforms I will use it to update the ReadMe and trigger a draft release to run a test.

Nice Work!

Thanks

**Comment by dougmassay** [comment]
Just note that a normal commit will only upload the build artifacts to appveyor's storage (like before I started custom deploying Sigil/PageEdit to gdrive). The compiled recourses will still be accessible via the normal appveyor build links, but only a tag push will create a draft-release on github and attach the resources to it.

When things settle down, I may make it so nothing builds automatically except new tags.

If a new set gets contributed, it should be as simple as adding the folder name to the list at the top of the build_resources.py script in ci_scripts. So long as the qrc is named the same as the folder, it should get picked up and compiled.

**Comment by dougmassay** [comment]
The appveyor image is compiling them with rcc from Qt5.6.3 LTS, by the way. That should make them compatible with just about anything out there, I figure.

**Comment by dougmassay** [comment]
> If you let me know what path or paths to put for both platforms I will use it to update the ReadMe and trigger a draft release to run a test.

If the config directory hasn't been changed with an environment variable override:

Linux :  ` ~/.local/share/sigil-ebook/sigil`
Windows:  `%localappdata%\sigil-ebook\sigil`

I'll delete the draft release that's currently there (and its tag) so you can trigger a release yourself.

**Comment by dougmassay** [comment]
Probably go with a 2020-10-10-2 since I did 1 2020-10-10-1 just after midnight last night. Or 2020.10.10.x or the like will work too. Just so long as the tag's not annotated or signed, really. Appveyor sees annotated/signed tags as branches for some reason. It's weird.

**Comment by kevinhendricks** [comment]
Okay, just tried it and all seemed to go well.  I updated the README.md, and created a tag "2020-10-10-2" as suggested and pushed it to upstream.

I checked and the new README.md is there and in Releases there is a new Draft Release made just one minute ago.

Great Work!

**Comment by dougmassay** [comment]
Good deal! Might as well make it an official release --though very few can actually use them yet. :)

**Comment by kevinhendricks** [comment]
Agreed!  I downloaded the legacy.rcc asset and installed it as custom_icon_theme.rcc and after restarting Sigil on my mac the Legacy icons are shown properly.  So the Qt 5.6 version of the rcc seems to work just fin on macOS.

So we should be good to go.

**Comment by dougmassay** [comment]
Easy-peasy!

So at this point, the only changes to main, fluent, and material should be if any tweaks to them flow from Sigil to here, right? This repo will be the definitive home for legacy and any future contributed sets. Code-wise, I mean.

**Comment by kevinhendricks** [comment]
Yes exactly!

**Comment by pgilfernandez** [comment]
Could you please release a new set of RCCs with the last commits that contain the new "remove tag pair" icon?

Thanks

**Comment by kevinhendricks** [comment]
Yes, it was long updated but I forgot to actually push the button to make the release official.

That has now been done.
